"""Export the complete MariaDB schema and production-safe seed data as SQL."""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = PROJECT_ROOT / "sql" / "init-mariadb.sql"
OFFLINE_DATABASE_URL = "mysql+pymysql://migration:placeholder@127.0.0.1:3306/lanying_jipai?charset=utf8mb4"
HEADER = """-- Blue Eagle Jipai MariaDB initialization script.
-- Generated from Alembic migrations. Do not edit this file manually.
-- Creates the schema, the default administrator, baseline platform configuration,
-- and the complete operations script library.
-- Default administrator: 1111111112 / admin@123. Change the password after first login.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

"""
TABLE_OPTIONS_PATTERN = re.compile(
    r"\)(?:CHARSET=utf8mb4 ENGINE=InnoDB|ENGINE=InnoDB CHARSET=utf8mb4) COLLATE utf8mb4_unicode_ci;"
)
CANONICAL_TABLE_OPTIONS = ")ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;"


def normalize_mariadb_sql(sql: str) -> str:
    """Make Alembic's equivalent table-option order deterministic."""
    return TABLE_OPTIONS_PATTERN.sub(CANONICAL_TABLE_OPTIONS, sql)


def export_init_sql(output: Path) -> None:
    environment = os.environ.copy()
    environment["DATABASE_URL"] = OFFLINE_DATABASE_URL
    environment["PYTHONIOENCODING"] = "utf-8"
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head", "--sql"],
        cwd=PROJECT_ROOT,
        env=environment,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "MariaDB initialization SQL export failed")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(HEADER + normalize_mariadb_sql(result.stdout), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export the complete MariaDB initialization SQL.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else Path.cwd() / args.output
    export_init_sql(output.resolve())
    print(f"MariaDB initialization SQL written to {output.resolve()}")


if __name__ == "__main__":
    main()
