-- Blue Eagle Jipai MariaDB initialization script.
-- Generated from Alembic migrations. Do not edit this file manually.
-- Creates the schema, the default administrator, baseline platform configuration,
-- and the complete operations script library.
-- Default administrator: 11111111112 / admin@123. Change the password after first login.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 20260728_01

CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    phone VARCHAR(20) NOT NULL, 
    password_hash VARCHAR(255) NOT NULL, 
    `role` ENUM('merchant','model','admin') NOT NULL, 
    nickname VARCHAR(50) NOT NULL, 
    avatar_url VARCHAR(255), 
    status ENUM('active','disabled') NOT NULL DEFAULT 'active', 
    real_name VARCHAR(50), 
    id_card_no VARCHAR(255), 
    alipay_account VARCHAR(100), 
    alipay_real_name VARCHAR(50), 
    verify_status ENUM('unverified','pending','verified','rejected') NOT NULL DEFAULT 'unverified', 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_users_phone UNIQUE (phone)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE UNIQUE INDEX ix_users_phone ON users (phone);

CREATE INDEX ix_users_role ON users (`role`);

CREATE TABLE merchant_profiles (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    user_id BIGINT NOT NULL, 
    shop_name VARCHAR(100) NOT NULL DEFAULT '', 
    shop_platform VARCHAR(50), 
    contact_phone VARCHAR(20) NOT NULL DEFAULT '', 
    default_ship_address VARCHAR(255) NOT NULL DEFAULT '', 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_merchant_profiles_user_id UNIQUE (user_id), 
    FOREIGN KEY(user_id) REFERENCES users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE model_profiles (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    user_id BIGINT NOT NULL, 
    height_cm SMALLINT, 
    weight_kg SMALLINT, 
    shoe_size VARCHAR(10), 
    skill_tags VARCHAR(255), 
    receive_address VARCHAR(255) NOT NULL DEFAULT '', 
    portfolio_urls TEXT, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_model_profiles_user_id UNIQUE (user_id), 
    FOREIGN KEY(user_id) REFERENCES users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO alembic_version (version_num) VALUES ('20260728_01');

-- Running upgrade 20260728_01 -> 20260728_02

CREATE TABLE orders (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    order_no VARCHAR(32) NOT NULL, 
    merchant_id BIGINT NOT NULL, 
    model_id BIGINT, 
    title VARCHAR(100) NOT NULL, 
    description TEXT NOT NULL, 
    sample_images TEXT, 
    commission_amount NUMERIC(10, 2) NOT NULL, 
    deposit_amount NUMERIC(10, 2) NOT NULL DEFAULT '0', 
    shoot_requirements TEXT, 
    status ENUM('DRAFT','PUBLISHED','CLAIMED','SHIPPED_TO_MODEL','IN_PROGRESS','RETURNED','COMPLETED','DISPUTED','CANCELLED') NOT NULL DEFAULT 'PUBLISHED', 
    ship_to_model_tracking_no VARCHAR(50), 
    ship_to_model_company VARCHAR(50), 
    return_tracking_no VARCHAR(50), 
    return_company VARCHAR(50), 
    submitted_media TEXT, 
    reject_reason TEXT, 
    claimed_at DATETIME, 
    shipped_at DATETIME, 
    in_progress_at DATETIME, 
    returned_at DATETIME, 
    completed_at DATETIME, 
    cancelled_at DATETIME, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_orders_order_no UNIQUE (order_no), 
    FOREIGN KEY(merchant_id) REFERENCES users (id), 
    FOREIGN KEY(model_id) REFERENCES users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX idx_orders_status ON orders (status);

CREATE INDEX idx_orders_merchant_id ON orders (merchant_id);

CREATE INDEX idx_orders_model_id ON orders (model_id);

CREATE TABLE order_logs (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    order_id BIGINT NOT NULL, 
    operator_id BIGINT NOT NULL, 
    from_status VARCHAR(30), 
    to_status VARCHAR(30) NOT NULL, 
    remark VARCHAR(255), 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    FOREIGN KEY(order_id) REFERENCES orders (id), 
    FOREIGN KEY(operator_id) REFERENCES users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX idx_order_logs_order_id ON order_logs (order_id);

CREATE TABLE order_messages (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    order_id BIGINT NOT NULL, 
    sender_id BIGINT NOT NULL, 
    content TEXT NOT NULL, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    FOREIGN KEY(order_id) REFERENCES orders (id), 
    FOREIGN KEY(sender_id) REFERENCES users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX idx_order_messages_order_id ON order_messages (order_id);

UPDATE alembic_version SET version_num='20260728_02' WHERE alembic_version.version_num = '20260728_01';

-- Running upgrade 20260728_02 -> 20260728_03

CREATE TABLE wallets (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    user_id BIGINT NOT NULL, 
    available_balance NUMERIC(10, 2) NOT NULL DEFAULT '0', 
    frozen_balance NUMERIC(10, 2) NOT NULL DEFAULT '0', 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_wallets_available_nonnegative CHECK (available_balance >= 0), 
    CONSTRAINT ck_wallets_frozen_nonnegative CHECK (frozen_balance >= 0), 
    CONSTRAINT uq_wallets_user_id UNIQUE (user_id), 
    FOREIGN KEY(user_id) REFERENCES users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE withdrawals (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    withdrawal_no VARCHAR(32) NOT NULL, 
    user_id BIGINT NOT NULL, 
    amount NUMERIC(10, 2) NOT NULL, 
    alipay_account VARCHAR(255) NOT NULL, 
    alipay_real_name VARCHAR(50) NOT NULL, 
    status ENUM('pending','approved','rejected','completed') NOT NULL DEFAULT 'pending', 
    reviewer_id BIGINT, 
    reject_reason VARCHAR(255), 
    transfer_no VARCHAR(100), 
    transferred_at DATETIME, 
    remark TEXT, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_withdrawals_amount_positive CHECK (amount > 0), 
    CONSTRAINT uq_withdrawals_withdrawal_no UNIQUE (withdrawal_no), 
    CONSTRAINT uq_withdrawals_transfer_no UNIQUE (transfer_no), 
    FOREIGN KEY(user_id) REFERENCES users (id), 
    FOREIGN KEY(reviewer_id) REFERENCES users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX idx_withdrawals_user_created ON withdrawals (user_id, created_at);

CREATE INDEX idx_withdrawals_status_created ON withdrawals (status, created_at);

CREATE TABLE wallet_transactions (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    idempotency_key VARCHAR(100) NOT NULL, 
    user_id BIGINT NOT NULL, 
    type ENUM('order_settlement','withdrawal_freeze','withdrawal_complete','withdrawal_reject_refund') NOT NULL, 
    amount NUMERIC(10, 2) NOT NULL, 
    balance_after NUMERIC(10, 2) NOT NULL, 
    frozen_balance_after NUMERIC(10, 2) NOT NULL, 
    order_id BIGINT, 
    withdrawal_id BIGINT, 
    remark VARCHAR(255), 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_wallet_transactions_idempotency_key UNIQUE (idempotency_key), 
    FOREIGN KEY(user_id) REFERENCES users (id), 
    FOREIGN KEY(order_id) REFERENCES orders (id), 
    FOREIGN KEY(withdrawal_id) REFERENCES withdrawals (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX idx_wallet_transactions_user_created ON wallet_transactions (user_id, created_at);

CREATE INDEX idx_wallet_transactions_order_id ON wallet_transactions (order_id);

CREATE INDEX idx_wallet_transactions_withdrawal_id ON wallet_transactions (withdrawal_id);

CREATE TABLE platform_configs (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    config_key VARCHAR(50) NOT NULL, 
    config_value VARCHAR(255) NOT NULL, 
    description VARCHAR(255), 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_platform_configs_config_key UNIQUE (config_key)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

UPDATE alembic_version SET version_num='20260728_03' WHERE alembic_version.version_num = '20260728_02';

-- Running upgrade 20260728_03 -> 20260728_04

ALTER TABLE users ADD COLUMN verify_reject_reason VARCHAR(255);

UPDATE alembic_version SET version_num='20260728_04' WHERE alembic_version.version_num = '20260728_03';

-- Running upgrade 20260728_04 -> 20260728_05

ALTER TABLE users MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE merchant_profiles MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE model_profiles MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE orders MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE wallets MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE withdrawals MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE platform_configs MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE alembic_version SET version_num='20260728_05' WHERE alembic_version.version_num = '20260728_04';

-- Running upgrade 20260728_05 -> 20260729_06

ALTER TABLE orders ADD COLUMN product_categories VARCHAR(255) NOT NULL DEFAULT '["其他"]';

UPDATE alembic_version SET version_num='20260729_06' WHERE alembic_version.version_num = '20260728_05';

-- Running upgrade 20260729_06 -> 20260730_07

CREATE TABLE media_backup_jobs (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    object_key VARCHAR(512) NOT NULL, 
    content_type VARCHAR(100) NOT NULL, 
    content_size BIGINT NOT NULL, 
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', 
    attempt_count INTEGER NOT NULL DEFAULT '0', 
    last_error TEXT, 
    last_attempt_at DATETIME, 
    next_retry_at DATETIME, 
    synced_at DATETIME, 
    created_at DATETIME NOT NULL DEFAULT now(), 
    updated_at DATETIME NOT NULL DEFAULT now(), 
    PRIMARY KEY (id), 
    UNIQUE (object_key)
);

CREATE INDEX ix_media_backup_jobs_object_key ON media_backup_jobs (object_key);

CREATE INDEX ix_media_backup_jobs_status ON media_backup_jobs (status);

CREATE INDEX ix_media_backup_jobs_next_retry_at ON media_backup_jobs (next_retry_at);

UPDATE alembic_version SET version_num='20260730_07' WHERE alembic_version.version_num = '20260729_06';

-- Running upgrade 20260730_07 -> 20260731_08

ALTER TABLE media_backup_jobs ADD COLUMN primary_storage VARCHAR(20) NOT NULL DEFAULT 'cos';

ALTER TABLE media_backup_jobs ADD COLUMN backup_storage VARCHAR(20) NOT NULL DEFAULT 'minio';

UPDATE alembic_version SET version_num='20260731_08' WHERE alembic_version.version_num = '20260730_07';

-- Running upgrade 20260731_08 -> 20260801_09

ALTER TABLE model_profiles ADD COLUMN receiver_name VARCHAR(50) NOT NULL DEFAULT '';

ALTER TABLE model_profiles ADD COLUMN receiver_phone VARCHAR(20) NOT NULL DEFAULT '';

ALTER TABLE model_profiles ADD COLUMN receive_address_detail VARCHAR(255) NOT NULL DEFAULT '';

UPDATE alembic_version SET version_num='20260801_09' WHERE alembic_version.version_num = '20260731_08';

-- Running upgrade 20260801_09 -> 20260802_10

ALTER TABLE orders ADD COLUMN order_type VARCHAR(30) NOT NULL DEFAULT 'product_photo';

ALTER TABLE orders ADD COLUMN quantity INTEGER NOT NULL DEFAULT '1';

ALTER TABLE orders ADD COLUMN required_media_count INTEGER NOT NULL DEFAULT '6';

ALTER TABLE orders ADD COLUMN delivery_days INTEGER NOT NULL DEFAULT '5';

ALTER TABLE orders ADD COLUMN deposit_required BOOL NOT NULL DEFAULT false;

ALTER TABLE orders ADD COLUMN return_required BOOL NOT NULL DEFAULT true;

CREATE TABLE order_applications (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    order_id BIGINT NOT NULL, 
    model_id BIGINT NOT NULL, 
    message VARCHAR(300), 
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', 
    reviewer_id BIGINT, 
    review_reason VARCHAR(255), 
    reviewed_at DATETIME, 
    created_at DATETIME NOT NULL DEFAULT now(), 
    updated_at DATETIME NOT NULL DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_order_application_model UNIQUE (order_id, model_id), 
    FOREIGN KEY(order_id) REFERENCES orders (id), 
    FOREIGN KEY(model_id) REFERENCES users (id), 
    FOREIGN KEY(reviewer_id) REFERENCES users (id)
);

CREATE INDEX ix_order_applications_order_id ON order_applications (order_id);

CREATE INDEX ix_order_applications_model_id ON order_applications (model_id);

CREATE INDEX ix_order_applications_status ON order_applications (status);

UPDATE alembic_version SET version_num='20260802_10' WHERE alembic_version.version_num = '20260801_09';

-- Running upgrade 20260802_10 -> 20260803_11

CREATE TABLE script_categories (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    code VARCHAR(50) NOT NULL, 
    name VARCHAR(100) NOT NULL, 
    description VARCHAR(255) NOT NULL DEFAULT '', 
    display_order SMALLINT NOT NULL, 
    is_restricted BOOL NOT NULL DEFAULT false, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_script_categories_code UNIQUE (code)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_script_categories_display_order ON script_categories (display_order);

CREATE TABLE script_documents (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    category_id BIGINT NOT NULL, 
    source_key VARCHAR(80) NOT NULL, 
    source_filename VARCHAR(255) NOT NULL, 
    title VARCHAR(150) NOT NULL, 
    markdown_body TEXT NOT NULL, 
    content_sha256 VARCHAR(64) NOT NULL, 
    section_count SMALLINT NOT NULL, 
    copy_block_count SMALLINT NOT NULL, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_script_documents_source_key UNIQUE (source_key), 
    CONSTRAINT uq_script_documents_source_filename UNIQUE (source_filename), 
    FOREIGN KEY(category_id) REFERENCES script_categories (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_script_documents_category_id ON script_documents (category_id);

INSERT INTO script_categories (id, code, name, description, display_order, is_restricted) VALUES (1, 'douyin_ops', '抖音运营话术', '私信拉新、回复跟进、导流与风控 SOP', 10, false);

INSERT INTO script_categories (id, code, name, description, display_order, is_restricted) VALUES (2, 'recruitment_training', '达人招新与教学', '招新物料、平台介绍、口播、社群和培训资料', 20, false);

INSERT INTO script_categories (id, code, name, description, display_order, is_restricted) VALUES (3, 'sensitive_category', '敏感品类话术', '仅限运营场景查看的成年、自愿、合规沟通内容', 30, true);

INSERT INTO script_documents (id, category_id, source_key, source_filename, title, markdown_body, content_sha256, section_count, copy_block_count) VALUES (1, 1, 'douyin-ops-scripts', 'douyin-ops-scripts.md', '抖音运营话术库', '# 蓝鹰寄拍 · 抖音运营话术库（管理端可复制版）

> **用途**：供管理端运营人员一键复制  
> **场景**：抖音私信招新 → 对方回复后跟进 → 加微信 → 引导访问网页 / 安装安卓 App  
> **原则**：合规优先、低刺激话术、先建立信任再导流、不承诺收益

---

## 0. 使用前必读（抖音风控）

### 0.1 运营纪律（必须遵守）

| 规则 | 说明 |
| --- | --- |
| 先互动后导流 | 首条私信**不发链接、不发微信号、不发二维码、不发 App 下载** |
| 等对方主动回 | 对方回复后，再进入「说明 → 加联系方式 → 发入口」 |
| 单日限量 | 同一账号避免高频同质私信；建议分时段、换话术、控数量 |
| 内容相关 | 只私信穿搭/好物/居家/学生/宝妈等相关账号，减少举报 |
| 不诱导关注变现 | 不说「关注领单」「私我日入」「加群躺赚」 |
| 不碰违规品类 | 不涉及刷单、返利、投资、医美整容承诺、色情擦边 |
| 统一身份 | 对外固定「蓝鹰寄拍官方/运营」，不冒充个人宝妈骗信任后硬推 |
| 记录可追溯 | 管理端记录：谁发的、何时发的、对方是否回复、是否加微、是否注册 |

### 0.2 高风险词（尽量避免）

```text
日入 / 月入过万 / 躺赚 / 稳赚 / 保底 / 提成很高
加微信 / 加V / 威信 / 薇信 / 扣扣 / 扫码
点链接 / 点开领取 / 下载就赚钱
刷单 / 垫付 / 先交保证金 / 培训费
免费领 / 限时名额马上没 / 不加就没了
```

### 0.3 低风险替代表达

| 高风险说法 | 建议替换 |
| --- | --- |
| 加微信详聊 | 方便的话留个联系方式，我把入驻说明发你 |
| 点这个链接赚钱 | 入口我发你，你自己打开看介绍再决定 |
| 日入 300+ | 按单结算，单笔以订单显示为准 |
| 单子多到爆 | 有合适单可以接，前期先帮你跑通流程 |
| 马上下载 App | 安卓的话我发安装说明，你按步骤自己装 |
| 不回就没机会 | 不着急，你方便再看 |

### 0.4 推荐转化路径（标准 SOP）

```text
阶段A 首条破冰私信（无链接、无微信、无下载）
   ↓ 对方回复任意内容
阶段B 简短说明 + 确认意向（仍可不发外链）
   ↓ 对方表示想了解 / 想试试
阶段C 邀约留联系方式（微信）——用低风险措辞
   ↓ 已加微信
阶段D 微信内发完整说明 + 网页入口 / App 安装说明
   ↓ 引导注册与完善资料
阶段E 跟进审核 / 首单辅导
```

**关键原则：抖音只负责“聊开”；注册、链接、App 尽量放到微信完成。**

---

## 1. 阶段 A｜首条破冰私信（仅 1 条机会）

> 要求：短、像人话、无外链、无微信号、以「回一个词」为行动点。

### A1 通用（推荐默认）

```text
你好呀，看你主页挺适合做「在家寄拍」：商家把样品寄到手上，按要求拍完上传，验收通过后按单结算。比较适合时间比较碎的姐妹。我们是蓝鹰寄拍官方，正在找认真想了解的达人。想看说明的话回我「了解」就行～
```

### A2 学生向

```text
你好～如果课余想找个不跑店的灵活事，可以了解下「寄拍」：样品寄到你这，拍完上传就行，按单结算。我们蓝鹰寄拍在招女生达人，不强迫、不收费了解。有兴趣回「了解」～
```

### A3 宝妈向

```text
宝妈你好～有个在家就能做的寄拍协作：样品寄到家，按要求拍完上传，验收后结算。适合见缝插针的时间。我们是蓝鹰寄拍，只找愿意认真了解的姐妹。想看怎么开始回「了解」～
```

### A4 穿搭/好物向

```text
你好，看你平时就爱拍东西，其实和「寄拍协作」挺像：商家寄样品，你按要求出图，验收后结算。我们蓝鹰寄拍在找拍摄达人。想看具体说明回「了解」就好～
```

### A5 更短版

```text
你好～蓝鹰寄拍在找在家拍摄的女生达人：商家寄样、拍摄上传、验收结算。想了解回「了解」，我按你情况说～
```

### A6 更稳妥（风控最保守）

```text
你好，我们是蓝鹰寄拍平台运营。平台做的是商家与拍摄达人的协作对接，流程都在平台内完成。若你有兴趣了解是否适合自己，可以回「了解」，我再说明，不打扰的话忽略即可。
```

---

## 2. 阶段 B｜对方已回复：先稳住，再推进

> 对方回了「了解 / 怎么做 / 要钱吗 / 单子多吗」等，**先答疑 1～2 句，再邀约留联系方式**。  
> 此阶段仍建议：抖音内少发外链。

### B1 对方回「了解 / 1 / 好的」

```text
好的～先说清楚三点：
1）入驻了解免费（不收培训费/加盟费）
2）模式是商家寄样→你拍摄上传→验收后按单结算
3）不保证每天都有单，但流程清楚，适合先跑通1单

你现在更方便看手机网页，还是安卓手机？我按你的方式发说明。
另外为了把入口和步骤发完整（抖音里容易发不全），你方便留个微信号吗？我备注「蓝鹰寄拍」加你。
```

### B2 对方回「是什么 / 怎么赚钱」

```text
简单说：不是让你转发任务，是真实寄样拍摄协作。
商家把样品寄给你 → 你按要求拍照/拍视频并上传 → 样品寄回 → 商家验收通过后，佣金按订单金额入账，再申请提现。

你要是觉得可以了解，我把完整入驻步骤发你。方便留个微信吗？我发网页入口/安卓安装说明（抖音里链接不稳定）。
```

### B3 对方回「要交钱吗 / 是不是骗子」

```text
理解你谨慎～我们说明白：
· 了解和入驻说明不收费
· 不要求你先垫钱给个人
· 订单、验收、结算都在平台流程里走，可追踪

你要是愿意看，我把平台介绍和入口发你，你自己打开看再决定。方便用微信接收吗？我备注官方身份加你。
```

### B4 对方回「单子多吗 / 能赚多少」

```text
实话实说：佣金看每笔订单显示金额，不是口头承诺月入。
平台前期更适合愿意先完善资料、认真交付的人；单量会逐步上，不拿“暴富”吸引你。

如果你接受「按单结算、先跑流程」，我再发入驻方式。方便留微信吗？材料比较完整，抖音一次发不完。
```

### B5 对方回「我是学生 / 宝妈，有时间吗」

```text
可以的，很多是课余/带娃间隙做，不是坐班打卡。
一般是有单再拍，拍完上传寄回即可；接单节奏自己把控（也受等级额度限制，新手先稳）。

我按你的身份发更合适的说明。你方便留个微信吗？我发入口，你自己注册看。
```

### B6 对方犹豫「再看看 / 不急」

```text
没关系，不着急～
你要是之后想看，随时回「了解」。
我也可以先发一段文字说明（不带链接），你看完再决定要不要留联系方式。
```

### B6 补充：仅文字说明（仍不发链接）

```text
【蓝鹰寄拍·文字说明】
角色：拍摄达人
流程：完善资料+实名 → 审核通过 → 抢单 → 收样品 → 拍摄上传 → 寄回 → 验收结算 → 申请提现
适合：学生/宝妈/居家女生，会手机拍照、能收发快递
说明：按单结算；不承诺固定收入；平台内流程可追踪

若要获取网页入口或安卓安装方式，回「要入口」，我再联系你发。
```

---

## 3. 阶段 C｜吸引对方留下微信 / 联系方式

> **目标**：让对方主动留微信号，或同意你加她。  
> **话术要点**：给理由（材料长、链接在抖音不稳定、要发安装包说明），降低防备。

### C1 标准邀约（推荐）

```text
好的，那我把「入驻步骤 + 网页入口 + 安卓安装说明」整理发你。
抖音里外链经常发不出去/打不开，所以一般改微信发完整版。

你可以直接发微信号给我，我备注【蓝鹰寄拍-你的昵称】添加；
或者你加我，我把我的号发你（二选一你方便哪个）。
```

### C2 更软、更低压力

```text
材料有点长，还要区分网页版和安卓版，抖音一次说不清。
你要是方便，留个联系方式，我发你自己看；不方便也没关系，我可以继续在这用文字答疑。
```

### C3 给选择（提高回复率）

```text
为了发入口方便，你选一个就行：
① 你发微信号，我加你
② 我发客服号，你通过后我发资料
③ 暂时不加，先在这问

回 1 / 2 / 3 就行～
```

### C4 对方不愿加微信

```text
完全理解～那我们先在这沟通。
你更想先看：入驻要什么资料、怎么接单、还是结算怎么走？
等你觉得OK了，再拿入口也不迟。
```

### C5 对方问「为什么要加微信」

```text
主要三个原因：
1）抖音对外部入口限制多，网页/安装说明经常发不全
2）后面审核、资料问题方便一对一协助（你也可以不回）
3）我们会发官方说明，不要求你转账给个人

你只用来接收资料也行，不想聊可以设置免打扰。
```

### C6 对方同意后，你发客服微信号

```text
好的，这是我们对接号：【在此填写微信号】
请备注：寄拍+抖音昵称
通过后我会发：
1）平台介绍
2）网页入口
3）安卓安装说明（如需要）
添加时认准备注，谨防仿冒。
```

### C7 安全提示（建议每次加微前后带一句）

```text
提醒：我们不会让你先转账、不会收保证金/培训费。若有人私聊让你付款，请立刻停止并告诉我。
```

---

## 4. 阶段 D｜已加微信后：导流网页 / 安卓 App

> **从这里开始可以发链接与安装说明。**  
> 运营在管理端替换：`【网页链接】` `【安卓下载链接】` `【客服微信】` `【有效期说明】`

### 4.1 加微成功 · 开场（必发）

```text
你好，我是蓝鹰寄拍运营，抖音沟通的那位。
先发三样，你按顺序看就行：

① 一分钟了解平台
商家寄样 → 你拍摄上传 → 寄回样品 → 验收通过后按单结算 → 申请提现

② 入驻需要
头像昵称、收货地址、作品集（至少6张）、实名信息（用于认证与提现）

③ 重要说明
· 了解/入驻说明免费
· 不保证固定收入
· 请只通过下方官方入口注册

你更方便用【手机网页】还是【安卓App】？回「网页」或「安卓」。
```

### 4.2 引导网页版（H5 / 达人端）

#### D-Web-1 标准

```text
【网页入口】
请用手机浏览器打开：
【网页链接】

建议步骤：
1. 打开链接
2. 注册/登录达人账号
3. 完善资料与作品集
4. 提交实名认证
5. 等待审核通过后进入抢单

若打不开：换系统浏览器（不要用微信内置页也可再试一次），或把截图发我帮你看。
```

#### D-Web-2 对方说「打不开 / 空白页」

```text
别急，按这个排查：
1）复制链接到手机自带浏览器打开
2）检查网络（切换 WiFi/流量）
3）若仍不行，发我截图+手机型号，我给你备用入口或安卓方式
```

#### D-Web-3 引导收藏/回到入口

```text
入口建议收藏，避免以后找不到。
你注册好后把「注册用的手机号后四位」回我，我帮你看资料是否提交完整。
```

### 4.3 引导安卓 App

#### D-App-1 标准

```text
【安卓App】
安装说明：
1. 点击下载：【安卓下载链接】
2. 若提示「未知来源」，在系统设置里允许本次安装即可
3. 安装后打开 App，使用达人账号登录
4. 完善资料 → 实名 → 等审核 → 抢单

注意：
· 请从我们发给你的官方链接下载
· 不要从陌生转发链接安装
· 我们不会要你付款才能安装
```

#### D-App-2 对方只有安卓且担心安全

```text
理解～App 是达人端封装（方便手机使用），账号体系与网页一致。
你也可以先用网页完成注册和资料，后续再装 App。
更稳妥顺序：先网页注册 → 再决定是否装 App。
网页：【网页链接】
```

#### D-App-3 安装失败

```text
常见处理：
1）下载完成后点文件安装
2）允许安装未知应用（仅本次）
3）清理旧包后重装
4）仍失败：发手机品牌+系统版本，我给你网页版先用
网页备用：【网页链接】
```

#### D-App-4 对方是 iPhone

```text
目前达人端安卓App更完整；iPhone 建议先用手机网页：
【网页链接】
用 Safari 打开后，可「添加到主屏幕」当快捷方式用。
```

### 4.4 双入口一起发（对方说都行）

```text
都可以，按你习惯选一个：

【方式A·网页】更轻，先体验
【网页链接】

【方式B·安卓App】常用安卓更方便
【安卓下载链接】

建议：先网页注册完善资料，安卓用户再装 App 登录同一账号即可。
```

---

## 5. 阶段 E｜注册后跟进（提高留存/首单）

### E1 询问是否注册成功

```text
你那边打开了吗？
如果已注册，回我：
1）是否已提交作品集
2）是否已提交实名
我帮你对一下还差哪步（差一步都过不了抢单）。
```

### E2 资料不完整

```text
审核前请确认：
□ 头像昵称
□ 收货省市区+详细地址+收件人电话
□ 作品集 ≥ 6 张（清晰即可）
□ 实名与支付宝信息按页面填写

缺哪项直接说，我按项教你。
```

### E3 审核中等待

```text
资料已提交的话耐心等审核即可。
通过后你就能进抢单大厅。
期间有问题随时发截图，我在这协助。
```

### E4 审核通过 · 首单激励（不夸大）

```text
恭喜通过～下一步很重要：先认真完成 1 单，把流程跑熟。
建议：
1）先看清拍摄要求再接
2）收货、拍摄、上传、寄回都在订单里操作
3）有异常及时在订单说明，不要私下答应改价/改需求

你现在打开大厅能看到单吗？看不到发截图我帮你看。
```

### E5 长时间未注册

```text
嗨，前两天发的入口你还有看吗？
不着急注册，但链接若过期我可以重发。
回「网页」或「安卓」我再发一次官方入口。
```

---

## 6. 场景速查表（运营可按标签复制）

| 场景标签 | 复制哪段 |
| --- | --- |
| 首条私信-通用 | A1 |
| 首条私信-学生 | A2 |
| 首条私信-宝妈 | A3 |
| 对方回了解 | B1 |
| 对方问怎么赚钱 | B2 |
| 对方防骗/要交钱吗 | B3 |
| 对方问收入单量 | B4 |
| 邀约加微-标准 | C1 |
| 邀约加微-三选一 | C3 |
| 不愿加微 | C4 |
| 加微开场 | 4.1 |
| 只要网页 | D-Web-1 |
| 只要安卓 | D-App-1 |
| iPhone | D-App-4 |
| 已注册跟进 | E1～E4 |

---

## 7. 管理端字段建议（方便配置）

运营后台「话术库」建议做成可变量模板：

| 变量名 | 示例 | 出现位置 |
| --- | --- | --- |
| `{{brand}}` | 蓝鹰寄拍 | 全阶段 |
| `{{wechat_id}}` | lanying_xxxx | C6、加微 |
| `{{web_url}}` | https://xxx/talent | D-Web |
| `{{android_url}}` | https://xxx/app.apk | D-App |
| `{{ops_name}}` | 小鹰 | 微信开场 |
| `{{no_fee_line}}` | 了解与入驻说明免费 | B/C/D |
| `{{reply_keyword}}` | 了解 | A 阶段 CTA |

**管理端展示建议：**

1. 按阶段分组：A破冰 / B回复 / C加微 / D导流 / E跟进  
2. 每条显示：场景名、风险等级（低/中）、一键复制  
3. 高风险操作（发外链、发微信号）加橙色提示：「仅在对方回复后 / 仅在微信内使用」  
4. 复制时自动替换变量；未配置变量则禁止复制并提示补全  

---

## 8. 完整示范对话（给新人运营看）

### 示范 1｜顺利转化

```text
运营A：你好呀，看你主页挺适合做「在家寄拍」……想看说明回「了解」～
用户：了解
运营B1：好的～先说清楚三点……你方便留个微信号吗？
用户：我微信 xxx
运营：好的，我备注蓝鹰寄拍加你；通过后发入口。
——转微信——
运营4.1：开场三件套 + 问网页还是安卓
用户：安卓
运营D-App-1：发安装说明
运营E1：问是否注册、资料是否完整
```

### 示范 2｜对方防备高

```text
用户：是不是要交钱
运营B3：解释不收费、不垫付、流程在平台
用户：那为啥要微信
运营C5：解释抖音发不全入口 + 安全提醒
用户：那你发号吧
运营C6：发客服号 + 防仿冒
——微信内只发官方入口，不催下载——
```

### 示范 3｜只愿留在抖音

```text
用户：不加微信
运营C4：表示理解，继续文字答疑
运营B6补充：发纯文字说明
用户：要入口
运营：可以，但抖音可能屏蔽链接；你若打不开，再考虑微信。先试：【仅当平台允许时再发短链】
```

> 若抖音消息直接发链接被拦截：不要连续重发同一链接，改为「回“网页”我换一种方式发」或转微信。

---

## 9. 风控自检清单（每次群发/私信前打勾）

```text
□ 首条是否不含微信/链接/二维码/下载？
□ 是否避免日入、躺赚、保底、刷单等词？
□ 是否说明不收费、不保证固定收入？
□ 是否等对方回复后再邀约联系方式？
□ 微信号是否只从官方配置读取（防个人乱加）？
□ 网页/App 链接是否为当前有效官方地址？
□ 是否提醒防仿冒、防转账？
□ 是否记录会话结果（回复/加微/注册）？
```

---

## 10. 一键复制区（精简版 · 可直接进管理端）

### 10.1 破冰默认

```text
你好呀，看你主页挺适合做「在家寄拍」：商家寄样到你手上，按要求拍完上传，验收后按单结算。我们是蓝鹰寄拍官方，想看说明回「了解」就行～
```

### 10.2 回复后转微信

```text
好的～模式是商家寄样→拍摄上传→验收按单结算；了解说明免费，不保证固定收入。
完整入口在抖音里经常发不全，你方便留个微信号吗？我备注「蓝鹰寄拍」加你，发网页/安卓两种方式你自己选。
```

### 10.3 微信开场 + 分流

```text
我是蓝鹰寄拍运营。先说明：免费了解、按单结算、不承诺固定收入；请只走官方入口。
回「网页」或「安卓」，我发对应方式。
```

### 10.4 网页

```text
网页入口：【网页链接】
步骤：打开→注册达人→完善资料与作品集→实名→等审核→抢单
打不开就复制到系统浏览器，或回我截图。
```

### 10.5 安卓

```text
安卓安装：【安卓下载链接】
允许本次安装→打开登录→完善资料实名。
也可先用网页注册同一账号：【网页链接】
```

### 10.6 安全句（随时可追加）

```text
我们不会让你先转账，也不会收保证金/培训费。若遇到要付款才能做单的人，请立刻停并告诉我。
```

---

## 11. 待运营配置（上线前填好）

| 项 | 填写 |
| --- | --- |
| 官方对接微信号 | |
| 微信号展示名/备注规则 | 蓝鹰寄拍-抖音昵称 |
| 达人网页入口 | |
| 安卓下载/安装页 | |
| 是否入驻免费（对外口径） | 是（建议） |
| 客服在线时段 | |
| 仿冒投诉处理人 | |

---

*版本：抖音运营话术 v1 · 风控友好 · 适用于管理端复制给运营人员*  
*与 `recruitment-copy.md` 配合使用：前者偏物料与招新文案，本稿偏私信转化 SOP。*
```
', 'dfbef0e0f9e77a49dfcd8878e0d49e6989a8bb316c69c7d89c184390faeb95d7', 12, 46);

INSERT INTO script_documents (id, category_id, source_key, source_filename, title, markdown_body, content_sha256, section_count, copy_block_count) VALUES (2, 2, 'recruitment-copy', 'recruitment-copy.md', '达人招新物料与教学', '# 蓝鹰寄拍 · 达人招新物料包

> 适用阶段：平台前期招新  
> 目标人群：女大学生、宝妈、待业/无主业女性、想做副业的居家人群  
> 核心卖点：在家寄拍、按单结算、时间自由、门槛低、平台流程保障  
> 使用原则：前期以「低压力、可尝试、真实可做」为主，不承诺固定月入、不夸张单量。

---

## 一、一句话定位

**蓝鹰寄拍：商家寄样品给你，你在家拍完上传，验收通过就结算佣金。**

适合：

- 学生党：课余时间可做
- 宝妈：孩子睡了也能拍
- 居家党：不用跑店、不用坐班
- 新手：不要求专业摄影棚，手机拍好也能接单

不适合承诺：

- 「躺赚」「日入过千」「保证月入 X 万」
- 虚构「每天 100 单」「全网都在抢」

---

## 二、推广海报（GPT Image 提示词）

> 当前本地图片生成额度不足，请把下面提示词直接复制到 **GPT Image / Midjourney / 即梦 / 可灵** 生成。  
> 建议：先出图，再在 Canva / 稿定设计上加中文文案，文字更清晰。

### 海报 A｜抖音竖版 9:16（主推）

**画面提示词（英文，出图更稳）：**

```text
A polished Chinese lifestyle recruitment poster for a product photography side hustle platform. Vertical 9:16 mobile poster. Soft cream, blush pink and light gold palette. A young East Asian woman at home casually photographing a fashion/beauty product on a clean desk near a window, natural daylight, relaxed confident smile. Modern clean commercial layout with large empty text space at top and bottom for Chinese headlines. Soft shadows, airy white space, trustworthy feminine aesthetic, not flashy, not luxury-glam, no watermark, high resolution.
```

**建议叠字文案：**

```text
主标题：在家也能接单赚钱
副标题：商家寄样 · 手机拍摄 · 验收结算
标签：学生党 / 宝妈 / 居家副业
底部 CTA：蓝鹰寄拍 · 达人招募中
```

### 海报 B｜朋友圈/小红书方图 1:1

**画面提示词：**

```text
A square 1:1 Chinese social media poster for home-based product photography talent recruitment. Soft pastel cream and peach tones. Collage of three warm lifestyle scenes: a college girl photographing a product, a young mom packing a small box, and a clean product flat-lay on a wooden table. Clean modern card layout, large empty headline area, friendly trustworthy brand feel, minimal decoration, soft natural light, high quality commercial design, no watermark.
```

**建议叠字文案：**

```text
主标题：不用出门，也能做副业
三利益点：时间自由 | 按单结算 | 平台流程保障
底部：蓝鹰寄拍 · 欢迎女生加入
```

### 海报 C｜「流程感」说明海报 9:16

**画面提示词：**

```text
A vertical educational marketing poster explaining a ship-and-shoot side job workflow. Clean cream background, soft pink and teal accent icons in four steps: receive package, photograph product at home, upload photos, get paid after acceptance. Modern Chinese app-style UI cards, soft shadows, friendly female lifestyle photography on the side, lots of white space for Chinese text overlays, trustworthy and simple, no clutter.
```

**建议叠字文案：**

```text
标题：4 步完成一单
1 收样品
2 按要求拍摄
3 上传素材并寄回
4 商家验收后结算
底部：蓝鹰寄拍 · 新手友好
```

### 海报 D｜宝妈向 9:16

**画面提示词：**

```text
A soft warm vertical poster targeting young Chinese moms for flexible home side income. Cozy living room, soft afternoon light, a young mom carefully photographing a small product on the coffee table while a toy is softly blurred in the background. Cream and warm peach palette, gentle and reassuring mood, clean commercial layout with empty space for Chinese text, no luxury glamour, no hard sell, high resolution.
```

**建议叠字文案：**

```text
主标题：带娃间隙，也能接一单
副标题：在家拍 · 按单结 · 不坐班
底部：蓝鹰寄拍 · 宝妈友好副业
```

### 出图后排版建议

| 元素 | 建议 |
| --- | --- |
| 主色 | 米白 `#FFF8F2` + 柔粉 `#F4B6C2` + 深灰字 `#2B2B2B` |
| 点缀 | 浅金 `#D4A574` 或薄荷绿 `#7DB8A0` |
| 字体 | 标题用圆润无衬线，正文清晰易读 |
| 避免 | 大红大绿、夸张「暴富」、密密麻麻数字 |
| 合规 | 不写「保证赚」「稳赚不赔」 |

---

## 三、抖音私信话术（只能发 1 条）

> 抖音私信常只能发一条，所以要：**短、清楚、不吓人、有行动指引**。  
> 目标不是一次讲完平台，而是让对方愿意回「想了解」或加微信/进群。

### 使用说明

1. 先看对方内容：学生、宝妈、探店、穿搭、好物分享更匹配
2. 语气像姐姐/朋友，不像推销员
3. 一条消息只做一件事：破冰 + 一句价值 + 一个动作
4. 不要一上来甩长文、链接堆、加很多表情

---

### 话术 1｜通用高转化（推荐）

```text
你好呀～看到你主页感觉挺适合做「在家寄拍」：商家把样品寄到你手上，你按要求拍完上传，验收通过就结算佣金。比较适合学生/宝妈这种时间碎片化的姐妹。我们平台叫蓝鹰寄拍，正在招新达人，想了解的话回我一句「想了解」，我把入驻方式和单子类型发你～
```

### 话术 2｜学生向

```text
学妹你好～如果你有空想做点不耽误课的副业，可以看看「寄拍」：不用跑店，商家寄样品，你在宿舍/家里拍完上传就行，按单结算。我们蓝鹰寄拍在招女生达人，门槛不高，新手也能试。感兴趣回「想了解」，我发你怎么入驻～
```

### 话术 3｜宝妈向

```text
宝妈你好～如果想找个不用出门、能见缝插针做的小副业，可以看看寄拍：商家寄样到家，你拍完上传，验收后结算。比较适合带娃间隙做。我们蓝鹰寄拍在招新，流程平台盯着，不要求你天天在线。想了解回「想了解」，我把怎么开始告诉你～
```

### 话术 4｜穿搭/好物博主向

```text
你好～看你平时就爱拍穿搭/好物，其实很适合做「寄拍接单」：商家寄产品给你拍，你按拍摄要求出图，验收通过结算佣金。比自己找商务更省心。我们蓝鹰寄拍在招达人，有兴趣回「想了解」，我发你平台说明～
```

### 话术 5｜更短版（怕被秒回/字数紧）

```text
你好～有个「在家寄拍」副业适合女生：商家寄样，你拍完上传，验收后结算。学生/宝妈都能做。蓝鹰寄拍招新中，想了解回我「1」，我发入驻方式～
```

### ~~话术 6~~｜更稳妥、少承诺版

```text
你好呀，我们是蓝鹰寄拍平台，在招在家拍摄的女生达人。模式是商家寄样品→你拍摄上传→商家验收后结算佣金，时间比较自由。不保证单量，但前期会带你走完入驻和接单流程。感兴趣的话回「想了解」～
```

### 私信后对方回复「想了解」时（第 2 轮，若可继续聊）

```text
好的～简单说下：
1）完善资料 + 实名认证
2）审核通过后进抢单大厅
3）抢到单后等商家寄样
4）拍摄上传并寄回样品
5）商家验收通过后佣金入账，可申请提现

你现在是学生、宝妈，还是居家想做副业？我按你情况说更合适的单子类型。
```

---

## 四、平台介绍话术（可发微信/社群/资料卡）

### 4.1 30 秒电梯版

```text
蓝鹰寄拍是一个「商家发单、达人接单」的寄拍平台。
商家把样品寄给你，你按要求拍好图/视频并上传，再把样品寄回。
商家验收通过后，平台给达人结算佣金。
适合学生、宝妈、居家女生：不用坐班、按单结算、时间相对自由。
```

### 4.2 完整介绍版（招新主文案）

```text
【蓝鹰寄拍 · 达人招新】

我们在找一批愿意在家接单的女生达人。

你要做的事很简单：
商家把样品寄到你手上 → 你按拍摄要求拍照/拍视频 → 上传素材并寄回样品 → 商家验收通过后结算佣金。

适合谁：
· 女大学生（课余可做）
· 宝妈（带娃间隙可做）
· 暂时没有主业、想做灵活副业的姐妹
· 会用手机拍照、愿意按要求出图的人

不适合谁：
· 想躺着日入过千的
· 完全不想寄收快递的
· 不愿意配合拍摄要求的

为什么前期适合加入：
1. 流程标准化：发单、抢单、寄样、交付、验收、结算都在平台内完成
2. 按单结算：做一单结一单，不搞复杂分成故事
3. 时间相对自由：不是坐班打卡制
4. 新手可成长：平台有达人等级，完成单越多，可接额度越高
5. 有平台保障：订单状态可追踪，验收/争议有平台介入，资金有流水记录

怎么开始：
注册达人账号 → 完善接单资料（头像、收货信息、作品集）→ 提交实名认证 → 审核通过后抢单
```

### 4.3 佣金怎么说（推荐口径）

> 真实系统逻辑：佣金由商家发单时填写；验收通过后入账；MVP 阶段平台不做抽佣扣减。  
> 达人等级会限制「同时进行中订单数」和「单笔佣金上限」。

**对外话术（稳妥）：**

```text
【关于佣金】
· 佣金按订单显示金额结算，不是口头说了算
· 商家验收通过后，佣金进入你的可提现余额
· 你可以在平台发起提现申请，审核通过后按平台流程处理
· 不同订单佣金不同，常见是按样品拍摄难度、件数、要求来定
· 新手一般从较低门槛单开始，先把流程跑熟，再接更高佣金单

【等级与接单额度】（可对认真询问的人说明）
L1 新星达人：刚起步，同时可接 1 单，单笔上限约 ¥300
L2 稳定达人：完成 5 单后，同时可接 2 单，单笔上限约 ¥800
L3 进阶达人：完成 20 单后，同时可接 3 单，单笔上限约 ¥1,500
更高等级随完成单数提升，额度更大

说明：等级是为了保护新手节奏和交付质量，不是卡人，而是让你稳步接单。
```

**不要这样说：**

```text
❌ 保底月入 8000
❌ 一单最少 500，随便拍拍就行
❌ 我们抽成很少，你能拿 90%（MVP 实际可不抽佣，但别编复杂故事）
❌ 单子多到抢不过来
```

### 4.4 单量怎么说（前期真实口径）

```text
【关于单量】
平台前期属于招新冷启动阶段，我们会持续引入商家发单。
目前更适合「愿意先入驻、先跑通 1～2 单」的姐妹。

你可以这样理解：
· 不是工厂流水线日接几十单
· 更像灵活副业：有合适单就接，接了就认真交付
· 前期我们更看重交付质量，质量稳定后，可接的单和额度会上来

如果你希望「有单通知 / 优先带新手」，入驻后把资料完善好，我们会优先给认真的人讲解和引导。
```

### 4.5 平台保证怎么说（信任点）

```text
【平台能保证什么】
1. 流程可追踪：订单从发布、抢单、寄出、拍摄、寄回、验收，状态都在系统里
2. 抢单规则公平：一单只能被一人抢走，避免私下扯皮
3. 结算有依据：验收通过后按订单佣金入账，有资金流水可查
4. 争议可处理：商家不通过时可进入争议，由平台介入仲裁
5. 提现有审核：提现申请走平台审核流程，不是私下转账口头承诺

【平台不保证什么】
· 不保证每天都有单
· 不保证每单都能过审（拍摄要按要求来）
· 不保证固定月收入
我们更强调：规则清楚、过程可查、结算可追溯。
```

### 4.6 入驻要求（降低顾虑）

```text
【入驻需要什么】
1. 基本资料：头像、昵称
2. 收货信息：省市区 + 详细地址 + 收件人 + 手机号（样品要寄到你）
3. 作品集：至少 6 张作品照（手机拍的好物/穿搭/静物都可以，先证明你会拍）
4. 实名认证：真实姓名、身份证、支付宝账号（用于后续提现）
5. 审核通过后，才能正式抢单

新手提示：
作品集不用影楼级，清晰、光线正常、构图干净就行。
先过审核，再在真实订单里练手。
```

### 4.7 一天怎么做（场景化）

**学生版：**

```text
晚上回宿舍拆个样品，按要求拍 20～40 分钟，上传素材，第二天寄回。
不冲突上课，也不用天天做。
```

**宝妈版：**

```text
孩子午睡或晚上安静时拍一拍，按清单出图。
不用跑外面，快递到家就能做。
```

**居家版：**

```text
你有一块干净桌面 + 自然光窗口就够起步。
先接简单单，熟悉流程后再冲更高佣金单。
```

---

## 五、短视频口播（抖音/视频号，15～25 秒）

### 口播 1｜通用

```text
女生找副业可以看看这个：
商家把样品寄到你家，你拍完上传，验收通过就结算。
不用坐班，学生宝妈都能做。
叫蓝鹰寄拍，主页/评论区可私信「寄拍」。
```

### 口播 2｜宝妈

```text
宝妈如果想做点不耽误带娃的事：
在家收个样品，拍完寄回，按单结算。
我知道的一个平台叫蓝鹰寄拍，正在招新。
想了解私信我「宝妈」。
```

### 口播 3｜避坑真诚风

```text
先说清楚：不是日入过千，是灵活副业。
寄拍就是商家寄样，你拍照上传，验收后结算。
适合有时间碎片、愿意认真出图的女生。
蓝鹰寄拍招达人，想了解私信「想了解」。
```

---

## 六、朋友圈 / 社群文案

### 朋友圈 1

```text
在招一批「在家寄拍」的女生达人
商家寄样 → 你拍摄上传 → 验收结算
比较适合学生、宝妈、居家党
不承诺暴富，但流程清楚、按单结算
想了解的扣 1，我发介绍
```

### 朋友圈 2

```text
有姐妹问副业，认真回一句：
如果你会用手机拍东西，愿意收发快递，
寄拍其实比很多「转发任务」实在。
蓝鹰寄拍在招新，私我「寄拍」
```

### 社群 annoucement

```text
【蓝鹰寄拍达人招募】
面向：女大学生 / 宝妈 / 居家灵活就业姐妹
模式：商家寄样 · 在家拍摄 · 验收结算
特点：按单结算、流程在平台内、有争议处理与资金流水
入驻：完善资料 + 作品集 + 实名认证
有意向请私聊「想入驻」，统一发送入驻指引
```

---

## 七、FAQ 速答（私信被追问时）

| 问题 | 建议回答 |
| --- | --- |
| 要交钱吗？ | 入驻不收加盟费/保证金话术请按你们实际政策；若无收费就明确说「入驻不收费」。 |
| 会不会骗？ | 订单、验收、结算都在平台流程里，提现走审核，不是让你私下打款给个人。 |
| 没拍过行吗？ | 可以，先准备 6 张作品集过审，从简单单开始。 |
| 多久能提现？ | 验收通过后佣金入账，再按平台提现审核流程处理（不要承诺「秒到」）。 |
| 单子多吗？ | 前期招新阶段，单量会逐步起来；先入驻跑通流程更重要。 |
| 样品坏了怎么办？ | 按订单要求保管与寄回；异常及时在订单内说明，由平台/商家按流程处理。 |
| 一定要出镜吗？ | 看订单要求，有的是静物拍，有的可能需要上身展示，以订单说明为准。 |

> 若你们**入驻完全免费**，请在所有话术里统一加一句：「入驻免费，不收培训费。」  
> 这是女性副业人群最敏感的信任点。

---

## 八、招新转化路径（建议执行）

```text
抖音内容种草
   ↓
私信 1 条破冰（回「想了解」）
   ↓
发「完整介绍版 + 入驻要求」
   ↓
引导注册 / 完善资料 / 交作品集
   ↓
审核通过
   ↓
带完成首单（最关键）
   ↓
用真实首单反馈继续邀约下一批
```

**前期 KPI 建议（务实）：**

- 私信通过率、资料提交率、审核通过率、**首单完成率**
- 先追求 20 个能交付的达人，再追求 200 个注册用户

---

## 九、可直接复制的「资料卡」长文

```text
蓝鹰寄拍｜女生达人招新说明

一、平台是做什么的
连接商家与达人的寄拍接单平台。
商家发布拍摄需求并寄出样品，达人拍摄上传并寄回，商家验收后平台结算佣金。

二、你怎么赚钱
按订单佣金结算。验收通过 → 佣金入账 → 申请提现。

三、适合谁
学生、宝妈、居家女生；会手机拍照；能收发快递；愿意按要求完成。

四、佣金与等级
佣金以订单显示为准；完成单数提升等级后，可同时进行的订单数和单笔上限会提高。
新手从 L1 起步更稳。

五、平台保障
订单状态可追踪；抢单防并发冲突；验收/争议可平台处理；资金变动有流水。

六、如何加入
1. 注册达人账号
2. 完善资料与作品集（≥6 张）
3. 提交实名认证
4. 审核通过后进入抢单大厅

七、诚实说明
前期为招新阶段，我们持续拓展商家单源。
不承诺固定收入，但承诺规则清楚、流程可查。
适合想认真做副业的人，不适合只想听暴富故事的人。

想加入请回复：想入驻
```

---

## 十、文案使用红线（务必遵守）

1. 不承诺固定月入、日入、躺赚  
2. 不虚构「今日 999 单」「全员月入过万」  
3. 不诱导「先交钱再赚钱」（若确无收费）  
4. 不贬低其他平台，不攻击个人  
5. 涉及身份证/支付宝，只说明「平台实名与提现需要」，强调信息用于认证结算  
6. 对未成年学生：强调课余、自愿、家长知情（如需要），不诱导逃课赚钱  

---

## 十一、你们可替换的变量位

生成对外物料前，请补全并统一：

| 变量 | 填写 |
| --- | --- |
| 达人端入口（H5/App/链接） | ________ |
| 客服微信 / 招新企微 | ________ |
| 是否入驻免费 | 是 / 否（建议：是） |
| 当前可公开的佣金区间示例 | 如：常见 ¥80–¥300（按实单） |
| 当前日均/周均可抢单量 | 只说真实区间或「持续上新」 |
| 提现到账时效口径 | 如：审核通过后 X 个工作日 |
| 招新截止/首批福利（如有） | 如：前 50 名优先带首单 |

---

*文档版本：招新 v1 · 面向学生/宝妈/居家女性 · 配合蓝鹰寄拍现有业务模式（寄样-拍摄-验收-结算-人工提现）*
```
', '04e79f1eaf6ddc0dfa95cf812b639c80a6bcdeace0ea66df855499dda0257fa5', 11, 33);

INSERT INTO script_documents (id, category_id, source_key, source_filename, title, markdown_body, content_sha256, section_count, copy_block_count) VALUES (3, 3, 'sensitive-category-scripts', 'sensitive-category-scripts.md', '敏感品类寄拍话术', '# 蓝鹰寄拍 · 敏感品类寄拍话术（文胸 / 情趣衣物）

> **适用范围**：品牌方寄拍涉及文胸、塑身、情趣风格衣物、贴身内衣等  
> **佣金口径**：通常为普通衣物的 **3～5 倍**（以订单页显示金额为准）  
> **使用原则**：先告知品类与拍摄边界 → 自愿确认 → 再引导抢单；**可随时拒单，零惩罚话术**  
> **对象**：仅面向 **已成年（18+）** 且完成实名认证的达人  
> **与普通招新区别**：不在抖音冷启动首条私信主推此类；优先在微信/站内、已建立信任后沟通

---

## 0. 运营红线（必须先读）

### 0.1 必须做到

| 规则 | 说明 |
| --- | --- |
| 事前明示 | 接单前必须说清：品类、是否需上身试穿、是否露脸、是否出镜全身 |
| 自愿原则 | 明确「不接完全不影响评级/后续普通单」 |
| 仅限成年 | 未满 18 岁、资料存疑一律不推、不派 |
| 订单内留痕 | 品类标签、拍摄要求、佣金写在订单里，不靠口头加码 |
| 尊重边界 | 达人可只接「平铺/挂拍/手持展示」，不强迫出镜试穿 |
| 隐私保护 | 素材仅用于该订单约定用途；不引导私下加商家微信传原图 |
| 平台内沟通 | 需求变更走订单留言，避免「加钱私下拍」 |

### 0.2 禁止话术

```text
❌ 不说清楚就让人抢单
❌ 「这单简单，穿一下就行」（淡化品类）
❌ 「不拍就别做了 / 会降权」（胁迫）
❌ 「多露一点更好过审 / 买家就爱看这个」
❌ 色情挑逗、约拍私单、线下见面拍摄
❌ 向未成年/学生党重点推送此类单
❌ 用「日入」「裸赚」等刺激词包装敏感单
❌ 要求达人先垫付购买情趣用品
```

### 0.3 品类分级（对内运营用，对外用「温和表述」）

| 级别 | 对内 | 对外可说 | 常见拍摄 | 佣金参考 |
| --- | --- | --- | --- | --- |
| S1 常规内衣 | 文胸、内裤、家居服 | 贴身衣物 / 内衣寄拍 | 平铺、上身（可要求不露脸） | 约 2～3 倍普通衣 |
| S2 塑身/情趣风格成衣 | 情趣风格套装、网纱、制服风格（非裸露） | 风格化服饰 / 特殊品类寄拍 | 上身出镜要求更细 | 约 3～5 倍 |
| S3 高敏感 | 强暗示、开档等极端款 | **默认不开放**或仅白名单达人 | 需法务/运营双审 | 单独定价 |

> 对外对达人：**少用「情趣」二字开场**（易引发防备或平台敏感），优先用「特殊品类贴身衣物 / 风格化内衣寄拍」，确认意向后再精确说明款式。

### 0.4 推荐沟通路径

```text
站内/微信（已信任达人）
  → 先发「品类预告 + 是否愿意看」
  → 对方回复愿意
  → 发「拍摄边界清单 + 佣金倍数说明 + 可拒单」
  → 对方明确「可接 / 仅平铺 / 不接」
  → 仅「可接」者看到或被引导对应订单
  → 抢单前二次确认关键项
```

**不要**在抖音首条破冰里主推敏感品类。

---

## 1. 预告话术（是否愿意看这类单）

### 1.1 微信 / 站内 · 标准预告（推荐）

```text
嗨，先跟你同步一个品类，你看完再决定要不要看单，完全自愿：

我们会有一些【贴身衣物 / 内衣类】品牌寄拍（含文胸，以及部分风格更特别的款）。
这类单拍摄要求更细，所以佣金一般是普通衣物的大约 3～5 倍（以订单显示为准）。

重要说明：
1）只发给成年且愿意了解的达人
2）不接不影响你继续接普通单
3）可只接「平铺/不露脸」，也可以选择不上身

你方便回一个吗：
A. 可以了解，发我要求
B. 只接普通衣物
C. 再等等
```

### 1.2 更短版

```text
有一类【内衣/贴身衣物寄拍】，佣金通常比普通衣高约 3～5 倍，但拍摄边界更严，需你本人自愿。
不接完全没问题。想了解回「可以了解」，只想接普通单回「普通」。
```

### 1.3 已合作过、信任度高

```text
你之前交付比较稳定，想先问你一句（不勉强）：
品牌侧有内衣/特殊风格贴身款寄拍，佣金更高（常见约 3～5 倍普通衣），但必须事先说清是否上身、是否露脸。
你若接受「先看要求再决定」，我发边界清单；不接受当我没说，继续给你推普通单。
```

### 1.4 对方是学生党（谨慎）

```text
先确认：你是否已满 18 周岁且方便自主决定接单类型？
我们有一类贴身衣物寄拍，佣金更高，但只开放给明确自愿的成年达人。
若你更想做普通穿搭/静物，直接说「只要普通」，我不会再推这类。
```

> 未满 18 或无法确认：停止推送，仅普通品类。

---

## 2. 边界说明话术（对方回「可以了解」后必发）

### 2.1 完整边界清单（主话术 · 建议收藏为模板）

```text
【特殊品类寄拍说明 · 请仔细看】

一、品类
品牌寄拍可能包含：文胸、内衣套装、塑身/风格化贴身衣物等。
具体以每一单的「商品说明 + 拍摄要求」为准，下单前你能看到。

二、佣金
同类单佣金通常约为普通衣物的 3～5 倍。
最终以订单页佣金金额为准，不接受口头加价、不私下收付款。

三、拍摄方式（你可按单选择）
① 平铺/挂拍/细节图（不上身）
② 上身试穿但不露脸（出镜局部/裁切）
③ 上身试穿且需露脸/半身（要求会写在订单里）
没有写进订单的要求，你可以拒绝。

四、我们明确不要求
· 不要求裸露超出资质与订单约定
· 不要求线下见面、私单加拍
· 不要求把原图发到个人微信给陌生人
· 不要求先垫钱买样品（样品由商家寄出）

五、你的权利
· 预告阶段可直接说不接
· 看到订单后仍可不抢
· 抢单前发现与描述不符，可立即联系运营说明
· 拒绝对你后续普通单没有惩罚话术、不因此降权承诺

六、隐私与用途
素材仅用于该订单约定的商品展示/验收；
平台内沟通与上传，保留记录便于维权。

若你接受「在规则内自愿接单」，请回复：
「已知晓，可按边界接单」
若只接受平铺：回复「仅平铺」
若全部不接：回复「不接特殊品类」
```

### 2.2 佣金单独说明（对方只关心钱）

```text
关于佣金（特殊品类）：
· 因为拍摄配合度、表达分寸、退换风险更高，品牌预算通常更高
· 平台侧常见是普通衣物单的约 3～5 倍
· 例：普通衣物若一单 80～150，特殊品类可能到约 240～750 区间（举例理解，下单以页面为准）
· 结算规则不变：验收通过 → 入账 → 申请提现
· 不会因为「尺度大」再额外私下转钱；一律走订单

你更在意「高一点但要求清晰」，还是「只要普通衣」？我按你的选择匹配。
```

### 2.3 只做平铺的达人

```text
可以，很多姐妹只接「平铺/细节/挂拍」：
不上身、不露脸，按商品图规范拍清楚版型、面料、钩扣、花边即可。
这类也会标佣金（通常仍高于普通衣，但可能低于必须上身的单）。
你回复「仅平铺」后，我优先只给你看标注了平铺可完成的单。
```

### 2.4 可上身但不露脸

```text
明白。订单里我们会尽量标注：
· 需上身试穿
· 可不露脸 / 面部打码或构图避开
请你接单前再核对图片示例与文案；若商家临时要求露脸且订单未写，你有权拒绝补拍并找运营。
```

---

## 3. 抢单前二次确认（强烈建议）

### 3.1 站内 / 微信确认

```text
这单属于【贴身衣物/特殊品类】，抢单前请确认：

1）商品类型：【文胸 / 套装 / 其他______】
2）拍摄：【仅平铺 / 需上身 / 需露脸】
3）佣金：¥【金额】（约普通衣 X 倍，仅供参考）
4）你已满 18 岁且自愿接单：是 / 否

请直接回复：
「确认抢单」或「放弃」

放弃无需解释，不影响普通单。
```

### 3.2 一句话确认（订单多时）

```text
特殊品类单 #【订单号】｜佣金¥【】｜【平铺/上身/露脸】
自愿才抢，不抢请忽略。确认请回「确认」。
```

---

## 4. 达人常见顾虑 · 应答

### 4.1 「是不是很色情 / 很尴尬」

```text
理解这个担心。我们按「商品拍摄」来做，不是擦边直播。
订单会写清拍什么角度、是否上身；你也可以只接平铺。
不舒服的要求可以不接，我们更在意合规和你的边界，不在意硬推尺度。
```

### 4.2 「照片会不会被乱用」

```text
请只在平台订单内上传；不要按陌生人要求改发个人号。
用途以订单约定的商品展示/验收为主。
若遇到有人引导「加微信多拍私单」，直接拒绝并告诉我。
```

### 4.3 「家里人会看到快递」

```text
外包装一般按普通服装快递，但无法 100% 保证面单品名如何打印。
若你家庭环境不方便收贴身类包裹，建议选择不接，或只接你确定能独立签收的时段。
这点以你实际生活便利为准，我们尊重。
```

### 4.4 「会不会要我买下来」

```text
寄拍是商家寄样，按流程拍摄后寄回（订单会写清是否需寄回）。
不要求你付款购买；若有人让你先转账，一律当异常，停止并举报给我。
```

### 4.5 「佣金真有 3～5 倍吗」

```text
这是品类预算上的常见区间，用来帮你建立预期；
每一单以订单页写明的佣金为准，可能更高或略低。
我们不会用「保证 5 倍」逼你接单。
```

### 4.6 「接了以后可不可以中途不做」

```text
抢单成功后请尽量完成（涉及商家已寄样等）。
若尚未寄出、或样品与描述严重不符、或出现超出资质的违规要求：立刻在订单留言并联系运营，我们按规则处理，不让你硬扛。
所以更稳妥是：抢单前看清要求。
```

### 4.7 「我可以接，但不要把我标成情趣达人」

```text
可以。对内只做订单匹配，不会在普通招新里宣传你的个人标签。
你也可以设置「可接特殊品类 / 仅平铺 / 关闭特殊品类」，我们按你的意愿来。
```

---

## 5. 拒单与关闭品类（保护体验）

### 5.1 达人表示不接

```text
收到，已记录：不推送特殊品类。
你继续接普通衣物/日用品即可。
以后若改变主意，随时说「可了解特殊品类」。
```

### 5.2 达人接过一次后不想再接

```text
没问题，立刻帮你关掉特殊品类匹配。
你的普通单权益不受影响，感谢你如实说边界。
```

### 5.3 达人反感被多次推送

```text
抱歉打扰了。已停止向你发送该类预告。
若是我们话术让你不适，也可以直接说，我们会改。
```

---

## 6. 拍摄执行提醒（已接单达人）

### 6.1 开拍前

```text
开拍前建议：
1）再读一遍拍摄清单（件数、角度、是否上身）
2）光线干净、背景简洁，按商品图逻辑拍
3）上身单注意：仪态自然、不夸张挑逗；按「电商详情图」标准，不按擦边短视频标准
4）不要额外拍摄订单未要求的暴露内容
5）有疑义先留言，再拍
```

### 6.2 商家临时加码尺度

```text
若商家通过留言/私下要求增加订单未写明的暴露内容：
请不要执行。回复「请以订单拍摄要求为准」，并 @ 运营。
超范围需求要么走平台变更（含佣金），要么拒绝。
```

### 6.3 交付话术（达人可复制给订单留言）

```text
素材已按订单要求上传，请验收。
如需补拍，请说明具体镜头（仍须在原订单约定范围内）。
```

---

## 7. 抖音场景（谨慎使用）

> 敏感品类 **不建议** 作为抖音冷私信主推内容。  
> 仅当对方已是达人、在站内/微信沟通时处理。若必须在抖音提及，用最低刺激表述。

### 7.1 抖音内点到为止（已互相关注/已回复）

```text
对了，平台偶尔有【贴身衣物类】寄拍，佣金更高，但完全自愿、需成年。
这类说明比较细，我在微信发边界清单更合适。不感兴趣忽略即可，不影响普通单。
```

### 7.2 禁止在抖音发送

```text
❌ 情趣、开档、诱惑、反差、裸感 等词堆砌
❌ 对比图、尺度示例图
❌ 「拍这个来钱快」
❌ 直接甩商品细节图
```

---

## 8. 运营内部匹配话术（管理端备注）

```text
【达人特殊品类意愿】
□ 关闭（不推送）
□ 仅平铺
□ 可上身不露脸
□ 可上身可露脸（白名单）
□ 已满 18 岁实名
□ 最近一次确认日期：____
□ 备注：____
```

派单前检查：

```text
□ 订单已标品类与拍摄方式
□ 佣金已填且与普通单有合理价差
□ 达人意愿标签匹配
□ 无未成年风险
□ 无「私下加钱」备注
```

---

## 9. 管理端一键复制区（精简）

### 9.1 预告

```text
有一类【贴身衣物/内衣寄拍】，佣金常约普通衣 3～5 倍（以订单为准），需成年自愿。不接不影响普通单。想了解回「可以了解」；只要普通回「普通」。
```

### 9.2 边界确认

```text
特殊品类说明：可能含文胸等贴身款；拍摄分平铺/上身/是否露脸，以订单为准；佣金约 3～5 倍普通衣但以页面为准；不要求私单、不垫付、不超范围暴露。可随时不抢。回复「已知晓，可按边界接单」/「仅平铺」/「不接特殊品类」。
```

### 9.3 抢单前

```text
本单为贴身/特殊品类｜佣金¥__｜拍摄：平铺/上身/露脸__｜请确认已满18且自愿。回「确认抢单」或「放弃」。放弃无惩罚。
```

### 9.4 拒单安抚

```text
已记录不推送特殊品类，普通单照常。需要时你再说「可了解」即可。
```

### 9.5 安全句

```text
全程平台内交付。不会要求你先转账。遇到加微信私单、加钱加尺度，直接拒绝并告诉运营。
```

---

## 10. 话术变量（管理端配置）

| 变量 | 含义 | 示例 |
| --- | --- | --- |
| `{{mult_min}}` | 佣金倍数下限 | 3 |
| `{{mult_max}}` | 佣金倍数上限 | 5 |
| `{{order_commission}}` | 本单佣金 | 399 |
| `{{shoot_type}}` | 拍摄类型 | 上身不露脸 |
| `{{product_type}}` | 商品类型 | 文胸套装 |
| `{{order_no}}` | 订单号 | JP2026… |
| `{{only_flat_ok}}` | 是否可平铺完成 | 是/否 |

---

## 11. 与普通招新话术的配合方式

| 场景 | 用哪份文档 |
| --- | --- |
| 抖音拉新、加微、下 App | `douyin-ops-scripts.md` |
| 普通佣金/平台介绍 | `recruitment-copy.md` |
| 文胸/情趣风格等特殊品类 | **本文档** |

**建议产品侧（若尚未做）：**

1. 订单增加「品类敏感等级 + 拍摄方式」字段，大厅可筛选/提示  
2. 达人资料增加「特殊品类意愿」：关闭 / 仅平铺 / 可上身  
3. 抢单二次确认弹窗：复述品类与是否上身  
4. 管理端话术库单独分组：**特殊品类**，权限仅运营可见  

---

## 12. 合规备忘（给负责人）

1. 内容应定位为 **合法成人商品的电商拍摄**，不是色情服务中介  
2. 达人侧强调 **劳动报酬按单结算**，不是「打赏/陪伴」  
3. 素材审核按电商图规范，拒绝违规暴露  
4. 保留达人「已知晓/仅平铺/不接」回复记录，降低纠纷  
5. 若涉及更极端款式，先法务评估再上架，不靠话术硬盖  

---

*版本：特殊品类沟通 v1 · 自愿 · 事前明示 · 高佣金如实说明 · 可拒单*  
*放置建议：管理端「话术库 → 特殊品类」分组，仅对运营角色开放复制*
```
', '018e2b19c6ed9115c6a4bcf21ea3caea1e1e39ba8a625d6e76ebd8069966398c', 13, 34);

UPDATE alembic_version SET version_num='20260803_11' WHERE alembic_version.version_num = '20260802_10';

-- Running upgrade 20260803_11 -> 20260804_12

INSERT INTO users (phone, password_hash, role, nickname)
        SELECT '11111111112', '$2b$12$6Oh.KUfvzK6jVUNXVUGFr.uM0nEGo1DE1FYDft/meK/uF/gbQu.A6', 'admin', '超级管理员'
        WHERE NOT EXISTS (SELECT 1 FROM users WHERE phone = '11111111112');

INSERT INTO platform_configs (config_key, config_value, description)
        SELECT 'platform_name', '蓝鹰寄拍', '平台显示名称'
        WHERE NOT EXISTS (SELECT 1 FROM platform_configs WHERE config_key = 'platform_name');

INSERT INTO platform_configs (config_key, config_value, description)
        SELECT 'talent_portfolio_min_count', '6', '达人接单资料要求的最少作品照片数量'
        WHERE NOT EXISTS (SELECT 1 FROM platform_configs WHERE config_key = 'talent_portfolio_min_count');

UPDATE alembic_version SET version_num='20260804_12' WHERE alembic_version.version_num = '20260803_11';

-- Running upgrade 20260804_12 -> 20260805_13

ALTER TABLE orders ADD COLUMN product_source VARCHAR(30) NOT NULL DEFAULT 'merchant_ship';

ALTER TABLE orders ADD COLUMN product_subsidy_amount NUMERIC(10, 2) NOT NULL DEFAULT '0.00';

ALTER TABLE orders ADD COLUMN self_keep_after_shoot BOOL NOT NULL DEFAULT false;

ALTER TABLE order_applications ADD COLUMN owned_product_images TEXT;

ALTER TABLE merchant_profiles ADD COLUMN quality_merchant BOOL NOT NULL DEFAULT false;

ALTER TABLE merchant_profiles ADD COLUMN guarantee_deposit_paid BOOL NOT NULL DEFAULT false;

ALTER TABLE merchant_profiles ADD COLUMN guarantee_deposit_amount NUMERIC(10, 2) NOT NULL DEFAULT '0.00';

CREATE TABLE media_assets (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    owner_id BIGINT NOT NULL, 
    url VARCHAR(512) NOT NULL, 
    content_type VARCHAR(100) NOT NULL, 
    duration_seconds NUMERIC(10, 3), 
    created_at DATETIME NOT NULL DEFAULT now(), 
    updated_at DATETIME NOT NULL DEFAULT now(), 
    PRIMARY KEY (id), 
    FOREIGN KEY(owner_id) REFERENCES users (id), 
    UNIQUE (url)
);

CREATE INDEX ix_media_assets_owner_id ON media_assets (owner_id);

UPDATE alembic_version SET version_num='20260805_13' WHERE alembic_version.version_num = '20260804_12';

-- Running upgrade 20260805_13 -> 20260806_14

CREATE TABLE order_fulfillments (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    order_id BIGINT NOT NULL, 
    application_id BIGINT NOT NULL, 
    model_id BIGINT NOT NULL, 
    slot_no INTEGER, 
    status VARCHAR(30) NOT NULL DEFAULT 'CLAIMED', 
    product_source VARCHAR(30) NOT NULL DEFAULT 'merchant_ship', 
    return_required BOOL NOT NULL DEFAULT true, 
    self_keep_after_shoot BOOL NOT NULL DEFAULT false, 
    commission_amount NUMERIC(10, 2) NOT NULL DEFAULT '0.00', 
    product_subsidy_amount NUMERIC(10, 2) NOT NULL DEFAULT '0.00', 
    ship_to_model_tracking_no VARCHAR(50), 
    ship_to_model_company VARCHAR(50), 
    return_tracking_no VARCHAR(50), 
    return_company VARCHAR(50), 
    submitted_at DATETIME, 
    reviewed_at DATETIME, 
    claimed_at DATETIME, 
    shipped_at DATETIME, 
    in_progress_at DATETIME, 
    returned_at DATETIME, 
    completed_at DATETIME, 
    reject_reason TEXT, 
    created_at DATETIME NOT NULL DEFAULT now(), 
    updated_at DATETIME NOT NULL DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_order_fulfillment_model UNIQUE (order_id, model_id), 
    CONSTRAINT uq_order_fulfillment_slot UNIQUE (order_id, slot_no), 
    FOREIGN KEY(order_id) REFERENCES orders (id), 
    UNIQUE (application_id), 
    FOREIGN KEY(application_id) REFERENCES order_applications (id), 
    FOREIGN KEY(model_id) REFERENCES users (id)
);

CREATE INDEX ix_order_fulfillments_order_id ON order_fulfillments (order_id);

CREATE INDEX ix_order_fulfillments_model_id ON order_fulfillments (model_id);

CREATE INDEX ix_order_fulfillments_status ON order_fulfillments (status);

CREATE INDEX ix_order_fulfillments_order_status ON order_fulfillments (order_id, status);

CREATE TABLE fulfillment_submissions (
    id BIGINT NOT NULL AUTO_INCREMENT, 
    fulfillment_id BIGINT NOT NULL, 
    version INTEGER NOT NULL, 
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW', 
    media_urls TEXT NOT NULL DEFAULT '[]', 
    remark TEXT, 
    review_reason VARCHAR(255), 
    reviewer_id BIGINT, 
    submitted_at DATETIME, 
    reviewed_at DATETIME, 
    created_at DATETIME NOT NULL DEFAULT now(), 
    updated_at DATETIME NOT NULL DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_fulfillment_submission_version UNIQUE (fulfillment_id, version), 
    FOREIGN KEY(fulfillment_id) REFERENCES order_fulfillments (id), 
    FOREIGN KEY(reviewer_id) REFERENCES users (id)
);

CREATE INDEX ix_fulfillment_submissions_fulfillment_id ON fulfillment_submissions (fulfillment_id);

CREATE INDEX ix_fulfillment_submissions_status ON fulfillment_submissions (status);

UPDATE alembic_version SET version_num='20260806_14' WHERE alembic_version.version_num = '20260805_13';

-- Running upgrade 20260806_14 -> 20260807_15

ALTER TABLE order_messages ADD COLUMN fulfillment_id BIGINT;

ALTER TABLE order_messages ADD CONSTRAINT fk_order_messages_fulfillment_id FOREIGN KEY(fulfillment_id) REFERENCES order_fulfillments (id);

CREATE INDEX ix_order_messages_fulfillment_id ON order_messages (fulfillment_id);

UPDATE alembic_version SET version_num='20260807_15' WHERE alembic_version.version_num = '20260806_14';

-- Running upgrade 20260807_15 -> 20260808_16

ALTER TABLE users ADD COLUMN registration_channel VARCHAR(50);

UPDATE alembic_version SET version_num='20260808_16' WHERE alembic_version.version_num = '20260807_15';

